Added Week 10 lecture part A
Atcold/NYU-DLSP21 pull request #12
Opened 2021-05-18 02:11 UTC by malfusion

Authors: Srishti Bhargava (sb7261), Jude Naveen Raj Ilango (jni215)

2021-05-18 14:30 UTC, Atcold requested changes
Figures do not have captions.
All figures are 16 MB! Please, reduce the size to 1 MB in total. People are loading these pages from mobile phones…
Also, way too much text. Plz, summarise more.

2021-05-18 14:30 UTC, Atcold commented on docs/en/week10/10-1.md
> +2. Be robust to nuisance factors (should be able to differentiate trees in different conditions - weather, across years, lighting, etc)
Please, shrink. This is way too much text.

2021-05-18 14:30 UTC, Atcold commented on docs/en/week10/10-1.md
> +    f_{\theta}(I) = f_{\theta}(augment(I))
```suggestion
    f_{\theta}(I) = f_{\theta}(\text{augment}(I))
```
Here and elsewhere.

2021-05-18 14:30 UTC, Atcold commented on docs/en/week10/10-1.md
> +2. Finetune the entire pretrained network on the target task. This may be more suitable for a detection task.
Please, shrink.

2021-05-18 14:30 UTC, Atcold commented on docs/en/week10/10-1.md
> +- Hard to scale to millions of images, as storage also needs to scale to millions of features.
Plz, shrink.

2021-05-18 14:30 UTC, Atcold commented on docs/en/week10/10-1.md
> +
Plz, shrink.

2021-05-22 01:10 UTC, malfusion commented
Added all the changes you had mentioned. Please review

2021-05-22 01:38 UTC, Atcold requested changes
Very good, almost there.

2021-05-22 01:38 UTC, Atcold commented on docs/en/week10/10-1.md
> +MoCo, or, Momentum Contrast, is a contrastive method that utilizes a memory bank to maintain a momentum of activations. It works by using 2 encoders. The $f_{\theta}$ encoder is the encoder that need
`EMA` should be encapsulated into `\text{}` here and everywhere else. It's test, it's not the product of three variables.

2021-05-22 01:38 UTC, Atcold commented on docs/en/week10/10-1.md
> +The SwAV (Swapping Assignments between Views) algorithm is an online clustering method. The idea here is to maximize the similarity of a given image $I$ and augmentation of that image $augment(I)$ an
Please, use `\text{}` for **ALL** non-standard function names, here and everywhere else.

2021-05-22 01:38 UTC, Atcold commented on docs/en/week10/10-1.md
> +2 crops from an image are passed through the network to compute the corresponding codes. The $2^{nd}$ code is then predicted from the $1^{st}$ embedding and vice versa. This task forces the network t
`nd` is the product of `n` and `d`. Use `\text{}` if necessary. Here and everywhere else.

2021-05-22 01:38 UTC, Atcold commented on docs/en/week10/10-1.md
> +## Self Supervised Learning for Computer Vision
```suggestion
```

Remove duplicate.

2021-05-22 01:51 UTC, malfusion commented
Added the modifications

2021-05-22 02:13 UTC, Atcold approved these changes
Great, thanks!

2021-05-22 02:13 UTC, merged