[DLSP21] 10-2
Atcold/NYU-DLSP21 pull request #5
Opened 2021-05-10 17:38 UTC by MrPhiDAP

Week 10, Chapter 4 Barlow Twins

2021-05-14 03:16 UTC, Atcold commented
I'm confused. What is this?

2021-05-17 15:15 UTC, MrPhiDAP commented
Sorry professor for the confusion. I have changed the _config.yml to add the chapter barlow twins to week 10.

2021-05-17 15:16 UTC, MrPhiDAP commented
https://mrphidap.github.io/NYU-DLSP21/en/week10/10-4/

2021-05-17 19:04 UTC, Atcold requested changes
It looks very good, but I'm confused about what this is.
10–1 and 10–2 are part 1 and 2 of Ishan's lecture.
10-3 is my lab.
What is 10-4???

2021-05-17 19:04 UTC, Atcold commented on docs/en/week10/10-4.md
> +lecturer: Ishan Misra, Alfredo Canziani
```suggestion
lecturer: Ishan Misra
```

2021-05-18 00:43 UTC, MrPhiDAP commented
@krishnakarthik9 i added your part to complete 10-2.md

2021-05-18 00:51 UTC, MrPhiDAP commented
Alright @Atcold, i added @krishnakarthik9 to my pull request. This is the complete second part of week 10. Hence 10-2.md.

2021-05-18 00:58 UTC, MrPhiDAP commented
https://mrphidap.github.io/NYU-DLSP21/en/week10/10-2/

2021-05-18 14:16 UTC, Atcold requested changes
Very good. Figures do not have captions, though…
Also, feel free to invert also the first 6 ones. The 7th looks great!

2021-05-18 14:16 UTC, Atcold commented on docs/en/week10/10-2.md
> +$$ f_{\theta}^{student}(I) = f_{\theta}^{teacher}(augment(I))$$
```suggestion
$$ f_{\theta}^{\text{student}}(I) = f_{\theta}^{\text{teacher}}(\text{augment}(I))$$
```

2021-05-18 14:16 UTC, Atcold commented on docs/en/week10/10-2.md
> +Figure 17 Barlow-Twins Architecture
Maybe figure 7?

2021-05-18 15:08 UTC, MrPhiDAP commented
@krishnakarthik9 your part, please change the tables. If you need assistance, just contact me!

2021-05-19 02:55 UTC, krishnakarthik9 commented
Inverted images with lighter background and added captions. Changes are reflected here: https://mrphidap.github.io/NYU-DLSP21/en/week10/10-2/

2021-05-19 05:17 UTC, merged

2021-05-19 05:17 UTC, Atcold commented
Very good, thanks!